#!/usr/bin/env python3
"""Set up HS.HC.UI.Home InterClaw tab in a namespace.

Copies all HS.HC.UI.* classes from HSLIB into the target namespace's database
via sub-package + routine mappings, then pushes a modified HS.HC.UI.Home with
the InterClaw menu item.

This avoids modifying the read-only HSLIB database.

Usage:
    setup_interclaw_portal.py --server myserver --namespace CLAUDE1
    setup_interclaw_portal.py --server myserver --namespace CLAUDE3 --dry-run
"""

import sys as _sys, os as _os; _sys.path.insert(0, _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..', 'lib'))
import argparse
import os
import subprocess
import sys
import tempfile

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", "..", "..", ".."))
PYTHON = sys.executable  # use same python as caller

# Classes in the HS.HC.UI sub-package that must be copied
HSUI_CLASSES = [
    "HS.HC.UI.AssigningAuthorities",
    "HS.HC.UI.Home",
    "HS.HC.UI.Installer.Welcome",
    "HS.HC.UI.Template",
    "HS.HC.UI.Util",
]

# Include files that must be copied (generated by Zen page compilation)
HSUI_INCLUDES = [
    "HS.HC.UI.Home.inc",
]

# InterClaw additions to HS.HC.UI.Home
# AddInterClawMenu creates a collapsible "InterClaw" panel via AddMenuBranch,
# and GetInterClawItems populates its children.
INTERCLAW_METHODS = '''
/// Add the InterClaw menu branch to the finder array.
Method AddInterClawMenu(ByRef pData)
{
\tSet n = $Order(pData(""),-1) + 1
\tDo ..AddMenuBranch("InterClaw","AI Development Assistant",,"GetInterClawItems",,,.pData,.n)
}

/// Populate the InterClaw sub-menu items.
Method GetInterClawItems(pN1, ByRef pData)
{
\tSet tURLPrefix = $Select($IsObject($Get(%request)): %request.URLPrefix, 1: "")
\t// Embedded Assistant — main InterClaw UI
\tSet tLink = tURLPrefix _ "/ui/interop/interclaw/interop-editor/index.html"
\tDo ..AddOption("Embedded Assistant","Open the InterClaw embedded assistant",,tLink,,,,.pData,.n2,pN1)
\t// Chatbot — latest devlog
\tSet tLink = tURLPrefix _ "/ui/interop/interclaw/interop-editor/index.html?view=devlog"
\tDo ..AddOption("Chatbot","Read latest development log",,tLink,,,,.pData,.n2,pN1)
\t// Skill Editor — placeholder
\tDo ..AddOption("Skill Editor","Edit and manage InterClaw skills",$LB("",1),,,,,.pData,.n2,pN1)
\t// Settings — placeholder
\tDo ..AddOption("Settings","Configure InterClaw preferences",$LB("",1),,,,,.pData,.n2,pN1)
}'''

INTERCLAW_CALL = '\tDo ..AddInterClawMenu(.pData)'


def run(cmd, check=True, capture=True):
    """Run a subprocess, return stdout."""
    result = subprocess.run(
        cmd, cwd=PROJECT_ROOT, capture_output=capture, text=True
    )
    if check and result.returncode != 0:
        stderr = result.stderr.strip() if result.stderr else ""
        stdout = result.stdout.strip() if result.stdout else ""
        msg = stderr or stdout
        raise RuntimeError(f"Command failed: {msg}")
    return result.stdout.strip() if result.stdout else ""


def terminal(server, namespace, code):
    """Run ObjectScript via iris_terminal.py."""
    return run([
        PYTHON, os.path.join(SCRIPT_DIR, "iris_terminal.py"),
        "--server", server, "--namespace", namespace, "--code", code
    ])


def terminal_file(server, namespace, filepath):
    """Run a .cos script via iris_terminal.py."""
    return run([
        PYTHON, os.path.join(SCRIPT_DIR, "iris_terminal.py"),
        "--server", server, "--namespace", namespace, "--file", filepath
    ])


def get_doc(server, namespace, doc, output):
    """Pull a document from the server."""
    os.makedirs(os.path.dirname(output), exist_ok=True)
    return run([
        PYTHON, os.path.join(SCRIPT_DIR, "get_doc.py"),
        "--server", server, "--namespace", namespace,
        "--doc", doc, "--output", output
    ])


def put_doc(server, namespace, doc, input_path, compile=True, force=True):
    """Push a document to the server."""
    cmd = [
        PYTHON, os.path.join(SCRIPT_DIR, "put_doc.py"),
        "--server", server, "--namespace", namespace,
        "--doc", doc, "--input", input_path,
    ]
    if compile:
        cmd.append("--compile")
    if force:
        cmd.append("--force")
    return run(cmd, check=False)


def compile_docs(server, namespace, docs):
    """Compile a list of documents."""
    return run([
        PYTHON, os.path.join(SCRIPT_DIR, "compile.py"),
        "--server", server, "--namespace", namespace,
        "--docs", ",".join(docs)
    ])


def create_mappings(server, namespace, dry_run=False):
    """Create package mapping for HS.HC.UI in the target namespace.

    Only a package mapping is needed — the namespace's default routine DB
    is already the target database, so include files and generated
    intermediates are resolved there automatically.
    """
    db = namespace  # convention: DB name matches namespace name

    if dry_run:
        print(f"  [DRY RUN] Would create package mapping HS.HC.UI -> {db}")
        return True

    # Check if mapping already exists
    cos = (
        f'set exists=##class(Config.MapPackages).Exists("{namespace}","HS.HC.UI") '
        f'if exists {{ write "PKG_EXISTS" }} else {{ write "PKG_NEW" }}'
    )
    result = terminal(server, "%SYS", cos)

    if "PKG_EXISTS" in result:
        print(f"  Package mapping HS.HC.UI already exists in {namespace}")
    else:
        cos_create = (
            f'set props("Database")="{db}" '
            f'set sc=##class(Config.MapPackages).Create("{namespace}","HS.HC.UI",.props) '
            f'write $select($system.Status.IsError(sc):"ERROR:"_$system.Status.GetErrorText(sc),1:"OK")'
        )
        result = terminal(server, "%SYS", cos_create)
        if "ERROR" in result:
            print(f"  FAILED to create package mapping: {result}")
            return False
        print(f"  Created package mapping HS.HC.UI -> {db}")

    return True


def patch_home_cls(source_path):
    """Patch HS.HC.UI.Home.cls to add the InterClaw menu item.

    Returns path to patched file (temp file).
    """
    with open(source_path, "r") as f:
        content = f.read()

    # Check if already patched
    if "AddInterClawMenu" in content or "AddInterClawItem" in content:
        print("  HS.HC.UI.Home already contains InterClaw — skipping patch")
        return source_path

    # Add call before both Quit sc exits in GetFinderArray
    # Pattern 1: ManageEnsemble path — "Catch {}\n\t\tQuit sc"
    content = content.replace(
        "\t\tCatch {}\n\t\tQuit sc",
        f"\t\tCatch {{}}\n{INTERCLAW_CALL}\n\t\tQuit sc"
    )

    # Pattern 2: Normal path — "} Catch ex {\n\t\tSet sc = ex.AsStatus()\n\t}\n\tQuit sc\n}"
    content = content.replace(
        "\t} Catch ex {\n\t\tSet sc = ex.AsStatus()\n\t}\n\tQuit sc\n}",
        f"\t}} Catch ex {{\n\t\tSet sc = ex.AsStatus()\n\t}}\n{INTERCLAW_CALL}\n\tQuit sc\n}}"
    )

    # Add methods before final closing brace
    last_brace = content.rfind("\n}")
    if last_brace == -1:
        raise RuntimeError("Cannot find class closing brace")
    content = content[:last_brace] + "\n" + INTERCLAW_METHODS + "\n\n}" + "\n"

    # Write to temp file
    fd, tmp_path = tempfile.mkstemp(suffix=".cls")
    with os.fdopen(fd, "w") as f:
        f.write(content)

    return tmp_path


def main():
    parser = argparse.ArgumentParser(
        description="Set up InterClaw tab in HS.HC.UI.Home for a namespace"
    )
    parser.add_argument("--server", "-s", required=True, help="Server name")
    parser.add_argument("--namespace", "-n", required=True, help="Target namespace")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be done")
    args = parser.parse_args()

    ns = args.namespace.upper()
    server = args.server

    print(f"Setting up InterClaw portal tab for {ns} on {server}")
    print()

    # Step 1: Create package mapping
    print("Step 1: Creating package mapping...")
    if not create_mappings(server, ns, args.dry_run):
        sys.exit(1)
    print()

    # Step 2: Pull classes from HSLIB
    print("Step 2: Pulling HS.HC.UI classes from HSLIB...")
    tmp_dir = tempfile.mkdtemp(prefix="interclaw_portal_")

    for cls_name in HSUI_CLASSES:
        local_path = os.path.join(tmp_dir, cls_name.replace(".", "/") + ".cls")
        if args.dry_run:
            print(f"  [DRY RUN] Would pull {cls_name}.cls from HSLIB")
        else:
            get_doc(server, "HSLIB", f"{cls_name}.cls", local_path)
            print(f"  Pulled {cls_name}.cls")

    for inc_name in HSUI_INCLUDES:
        local_path = os.path.join(tmp_dir, inc_name.replace(".", "/"))
        if args.dry_run:
            print(f"  [DRY RUN] Would pull {inc_name} from HSLIB")
        else:
            get_doc(server, "HSLIB", inc_name, local_path)
            print(f"  Pulled {inc_name}")
    print()

    if args.dry_run:
        print("Step 3: [DRY RUN] Would patch HS.HC.UI.Home with InterClaw tab")
        print("Step 4: [DRY RUN] Would push all classes to", ns)
        print("Step 5: [DRY RUN] Would compile all classes in", ns)
        print()
        print("Dry run complete. Run without --dry-run to apply.")
        return

    # Step 3: Patch Home.cls
    print("Step 3: Patching HS.HC.UI.Home with InterClaw tab...")
    home_source = os.path.join(tmp_dir, "HS/HC/UI/Home.cls")
    patched_home = patch_home_cls(home_source)
    print("  Patched successfully")
    print()

    # Step 4: Push include file first, then all classes
    print("Step 4: Pushing to", ns, "...")

    # Push include file first
    for inc_name in HSUI_INCLUDES:
        inc_path = os.path.join(tmp_dir, inc_name.replace(".", "/"))
        result = put_doc(server, ns, inc_name, inc_path, compile=False, force=True)
        print(f"  Pushed {inc_name}")

    # Push classes (use patched Home)
    for cls_name in HSUI_CLASSES:
        if cls_name == "HS.HC.UI.Home":
            input_path = patched_home
        else:
            input_path = os.path.join(tmp_dir, cls_name.replace(".", "/") + ".cls")
        result = put_doc(server, ns, f"{cls_name}.cls", input_path, compile=False, force=True)
        print(f"  Pushed {cls_name}.cls")
    print()

    # Step 5: Compile all classes
    print("Step 5: Compiling...")
    doc_list = [f"{c}.cls" for c in HSUI_CLASSES]
    try:
        compile_docs(server, ns, doc_list)
        print("  All classes compiled successfully")
    except RuntimeError as e:
        print(f"  Compilation error: {e}")
        sys.exit(1)

    print()
    print(f"Done! InterClaw tab is now available in {ns}.")
    print(f"Access it at: HS.HC.UI.Home.cls in the {ns} namespace.")

    # Cleanup temp patched file
    if patched_home != home_source:
        os.unlink(patched_home)


if __name__ == "__main__":
    main()
